CREATE TABLE DEPARTMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    salary INT,
    department_id INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (department_id) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30),
    role_id INT NOT NULL,
    manager_id INT,
    PRIMARY KET (ID),
    FOREIGN KEY (role_id) REFERENCES ROLE(ID),
    FOREIGN KEY (manager_id) REFERENCES EMPLOYEE(ID)
);
